use clap::Parser;

#[derive(Parser)]
#[command(version, about)]
pub(crate) struct Cli {
    /// Process name to iterate over
    #[arg(short, long, value_name = "PROCESS.EXE")]
    pub(crate) process_name: String,

    /// Specific module inside the process, if not set all available modules are considered
    #[arg(short, long)]
    pub(crate) module_name: Option<String>,

    /// Signature to find
    #[arg(short, long, value_name = "SIGNATURE")]
    pub(crate) signature: String,

    /// Ignores system related modules (does not bring anything if module_name option is set)
    #[arg(short, long, default_value = "false")]
    pub(crate) ignore_os: bool,
}

use std::collections::HashSet;

pub const IGNORED_MODULES: once_cell::unsync::Lazy<HashSet<&'static str>> =
    once_cell::unsync::Lazy::new(|| {
        HashSet::from([
            "ntdll.dll",
            "kernel32.dll",
            "kernelbase.dll",
            "user32.dll",
            "win32u.dll",
            "gdi32.dll",
            "gdi32full.dll",
            "msvcp_win.dll",
            "ucrtbase.dll",
            "imm32.dll",
            "advapi32.dll",
            "msvcrt.dll",
            "sechost.dll",
            "rpcrt4.dll",
            "ole32.dll",
            "combase.dll",
            "oleaut32.dll",
            "psapi.dll",
            "cfgmgr32.dll",
            "winmm.dll",
            "wintrust.dll",
            "crypt32.dll",
            "msasn1.dll",
            "ws2_32.dll",
            "bcrypt.dll",
            "bcryptprimitives.dll",
            "shell32.dll",
            "iphlpapi.dll",
            "wintypes.dll",
            "dbghelp.dll",
            "vfbasics.dll",
            "vrfcore.dll",
            "verifier.dll",
            "vconcomm.dll",
            "mswsock.dll",
            "imagehlp.dll",
            "setupapi.dll",
            "version.dll",
            "secur32.dll",
            "shlwapi.dll",
            "sspicli.dll",
            "shcore.dll",
            "cryptbase.dll",
            "wininet.dll",
            "kernel.appcore.dll",
            "uxtheme.dll",
            "dwmapi.dll",
            "dxgi.dll",
            "powrprof.dll",
            "umpdc.dll",
            "dxcore.dll",
            "devobj.dll",
            "imemanager.dll",
            "d3d9.dll",
            "d3d11.dll",
            "d3dcompiler_47.dll",
            "cryptnet.dll",
            "wldp.dll",
            "drvstore.dll",
            "cryptsp.dll",
            "rsaenh.dll",
            "windows.storage.dll",
            "profapi.dll",
            "ntmarta.dll",
            "msctf.dll",
            "mscms.dll",
            "textinputframework.dll",
            "clbcatq.dll",
            "dataexchange.dll",
            "twinapi.appcore.dll",
            "coremessaging.dll",
            "coreuicomponents.dll",
            "apphelp.dll",
            "dcomp.dll",
            "mmdevapi.dll",
            "audioses.dll",
            "windows.ui.dll",
            "wsock32.dll",
            "usp10.dll",
            "vcruntime140.dll",
            "vcruntime140_1.dll",
            "msvcp140.dll",
            "avrt.dll",
            "resourcepolicyclient.dll",
            "shfolder.dll",
            "propsys.dll",
            "networkexplorer.dll",
            "nsi.dll",
            "dhcpcsvc6.dll",
            "dhcpcsvc.dll",
            "dnsapi.dll",
            "rasadhlp.dll",
            "wbemprox.dll",
            "wbemcomn.dll",
            "napinsp.dll",
            "wbemsvc.dll",
            "winrnr.dll",
            "winhttp.dll",
            "nlansp_c.dll",
            "wshbth.dll",
            "fwpuclnt.dll",
            "fastprox.dll",
            "amsi.dll",
            "userenv.dll",
            "mpoav.dll",
            "gpapi.dll",
            "winnsi.dll",
            "textshaping.dll",
            "directxdatabasehelper.dll",
            "microsoft.internal.warppal.dll",
            "amd_ags_x64.dll",
            "nvapi64.dll",
            "nvspcap64.dll",
            "nvppex.dll",
            "nvldumdx.dll",
            "nvgpucomp64.dll",
            "nvmessagebus.dll",
            "nvmemmapstoragex.dll",
            "nvwgf2umx.dll",
            "aticfx64.dll",
            "atiuxp64.dll",
            "atidxx64.dll",
            "amdihk64.dll",
        ])
    });
